// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnM94VRRisLiRlglC4AONAFBJ6AMy2kak',
    appId: '1:100969705107:android:615e4db7fc0a74c4b5e766',
    messagingSenderId: '100969705107',
    projectId: 'fbauthall',
    storageBucket: 'fbauthall.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDLljrr_AqsP_L5oU9odzwHlFHDto4X1pk',
    appId: '1:100969705107:ios:96973c6d63f449e7b5e766',
    messagingSenderId: '100969705107',
    projectId: 'fbauthall',
    storageBucket: 'fbauthall.appspot.com',
    iosBundleId: 'com.example.fbauthentication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDLljrr_AqsP_L5oU9odzwHlFHDto4X1pk',
    appId: '1:100969705107:ios:96973c6d63f449e7b5e766',
    messagingSenderId: '100969705107',
    projectId: 'fbauthall',
    storageBucket: 'fbauthall.appspot.com',
    iosBundleId: 'com.example.fbauthentication',
  );
}
